- hosts: sentry
  become: yes
  gather_facts: False
  pre_tasks:
# This task is needed for Ubuntu Xenial
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-simplejson)
      register: output
      changed_when: output.stdout != ""
      tags: always
    - setup: # aka gather_facts
  vars:
    db_sentry:
      name: sentry
      user: sentry
      password: sentry
    superuser_sentry:
      username: admin
      email: admin@none.com
      password: 12345
    sentry:
      server: sentry.local
      url: https://sentry.local
      secret_key: 'redacted'
    sentry_mail:
      host: localhost
      port: 25
      username: ''
      password: ''
      use_tls: false
    nginx:
      key: /etc/ssl/private/server.key
      cert: /etc/ssl/certs/server.crt
      dhparm: /etc/ssl/certs/dhparam.pem
  roles:
    - common
    - python
    - supervisor
    - role: nginx
      nginx_sites: none
    - postgres
    - backup
    - sentry

